import type { TripState } from './types'

export const SEED: TripState = {
  activeModule: 'setup',
  setup: {
    name: 'Alpine Ridge Weekend',
    destination: 'Lake Tahoe, CA',
    startDate: '2026-05-15',
    endDate: '2026-05-17',
    timezone: 'America/Los_Angeles',
    coverEmoji: '🏔️',
    description: 'Three crews converging on the ridge. Snow optional, memories mandatory.',
  },
  groups: [
    {
      id: 'grp-sf',
      name: 'SF Crew',
      color: '#388BFD',
      emoji: '🌉',
      members: ['Alex', 'Jordan', 'Sam'],
      origin: 'San Francisco, CA',
      originLat: 37.7749,
      originLng: -122.4194,
    },
    {
      id: 'grp-la',
      name: 'LA Squad',
      color: '#DA3633',
      emoji: '🌴',
      members: ['Taylor', 'Morgan', 'Casey', 'Riley'],
      origin: 'Los Angeles, CA',
      originLat: 34.0522,
      originLng: -118.2437,
    },
    {
      id: 'grp-lv',
      name: 'Vegas Contingent',
      color: '#D29922',
      emoji: '🎰',
      members: ['Drew', 'Jamie'],
      origin: 'Las Vegas, NV',
      originLat: 36.1699,
      originLng: -115.1398,
    },
  ],
  routes: [
    {
      id: 'rt-sf',
      groupId: 'grp-sf',
      color: '#388BFD',
      label: 'SF → Tahoe',
      departureTime: '2026-05-15T08:00',
      waypoints: [
        { id: 'wp-sf-1', label: 'San Francisco', lat: 37.7749, lng: -122.4194 },
        { id: 'wp-sf-2', label: 'Sacramento pit stop', lat: 38.5816, lng: -121.4944, note: 'Coffee + gas' },
        { id: 'wp-sf-3', label: 'Lake Tahoe', lat: 39.0968, lng: -120.0324 },
      ],
    },
    {
      id: 'rt-la',
      groupId: 'grp-la',
      color: '#DA3633',
      label: 'LA → Tahoe',
      departureTime: '2026-05-15T06:00',
      waypoints: [
        { id: 'wp-la-1', label: 'Los Angeles', lat: 34.0522, lng: -118.2437 },
        { id: 'wp-la-2', label: 'Fresno lunch stop', lat: 36.7378, lng: -119.7871, note: 'In-N-Out' },
        { id: 'wp-la-3', label: 'Lake Tahoe', lat: 39.0968, lng: -120.0324 },
      ],
    },
    {
      id: 'rt-lv',
      groupId: 'grp-lv',
      color: '#D29922',
      label: 'Vegas → Tahoe',
      departureTime: '2026-05-15T07:00',
      waypoints: [
        { id: 'wp-lv-1', label: 'Las Vegas', lat: 36.1699, lng: -115.1398 },
        { id: 'wp-lv-2', label: 'Tonopah', lat: 38.0673, lng: -117.2296, note: 'Fuel up' },
        { id: 'wp-lv-3', label: 'Lake Tahoe', lat: 39.0968, lng: -120.0324 },
      ],
    },
  ],
  itinerary: [
    {
      id: 'ev-1',
      date: '2026-05-15',
      time: '14:00',
      title: 'Everyone arrives at the cabin',
      type: 'lodging',
      groupIds: [],
      location: 'Alpine Ridge Cabin, Lake Tahoe',
    },
    {
      id: 'ev-2',
      date: '2026-05-15',
      time: '18:00',
      title: 'Bonfire + introductions',
      description: 'Get the fire going, introductions for anyone who hasn\'t met yet',
      type: 'activity',
      groupIds: [],
    },
    {
      id: 'ev-3',
      date: '2026-05-15',
      time: '20:00',
      title: 'Group dinner',
      type: 'meal',
      groupIds: [],
    },
    {
      id: 'ev-4',
      date: '2026-05-16',
      time: '09:00',
      title: 'Hiking: Eagle Falls Trail',
      description: '5.5 miles, moderate difficulty. Stunning lake views.',
      type: 'activity',
      groupIds: [],
    },
    {
      id: 'ev-5',
      date: '2026-05-16',
      time: '14:00',
      title: 'Kayaking at Sand Harbor',
      description: 'Rent kayaks at the state park. Crystal clear water.',
      type: 'activity',
      groupIds: [],
    },
    {
      id: 'ev-6',
      date: '2026-05-16',
      time: '19:00',
      title: 'BBQ at the cabin',
      type: 'meal',
      groupIds: [],
    },
    {
      id: 'ev-7',
      date: '2026-05-17',
      time: '09:00',
      title: 'Sunrise coffee on the deck',
      type: 'free',
      groupIds: [],
    },
    {
      id: 'ev-8',
      date: '2026-05-17',
      time: '11:00',
      title: 'Pack up and depart',
      type: 'travel',
      groupIds: [],
    },
  ],
  meals: [
    {
      id: 'ml-1',
      date: '2026-05-15',
      mealType: 'dinner',
      title: 'Arrival dinner — pasta bar',
      assignedGroupIds: ['grp-sf'],
      notes: 'SF crew is cooking. Vegetarian options needed for Jordan.',
      cost: 80,
    },
    {
      id: 'ml-2',
      date: '2026-05-16',
      mealType: 'breakfast',
      title: 'Pancake breakfast',
      assignedGroupIds: ['grp-la'],
      notes: 'LA squad has breakfast duty',
      cost: 60,
    },
    {
      id: 'ml-3',
      date: '2026-05-16',
      mealType: 'lunch',
      title: 'Trail picnic',
      assignedGroupIds: [],
      notes: 'Everyone brings their own snacks for the hike',
    },
    {
      id: 'ml-4',
      date: '2026-05-16',
      mealType: 'dinner',
      title: 'BBQ — grill masters',
      assignedGroupIds: ['grp-lv'],
      notes: 'Vegas crew grilling. Steaks + veg skewers.',
      cost: 150,
    },
    {
      id: 'ml-5',
      date: '2026-05-17',
      mealType: 'breakfast',
      title: 'Leftover brunch',
      assignedGroupIds: [],
      notes: 'Clear out the fridge before departure',
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      description: 'Cabin rental (3 nights)',
      amount: 900,
      currency: 'USD',
      paidBy: 'grp-sf',
      splitBetween: ['grp-sf', 'grp-la', 'grp-lv'],
      date: '2026-05-15',
      category: 'lodging',
    },
    {
      id: 'exp-2',
      description: 'Groceries — arrival dinner',
      amount: 80,
      currency: 'USD',
      paidBy: 'grp-sf',
      splitBetween: ['grp-sf', 'grp-la', 'grp-lv'],
      date: '2026-05-15',
      category: 'food',
    },
    {
      id: 'exp-3',
      description: 'Kayak rentals',
      amount: 240,
      currency: 'USD',
      paidBy: 'grp-la',
      splitBetween: ['grp-sf', 'grp-la', 'grp-lv'],
      date: '2026-05-16',
      category: 'activity',
    },
    {
      id: 'exp-4',
      description: 'BBQ groceries + charcoal',
      amount: 150,
      currency: 'USD',
      paidBy: 'grp-lv',
      splitBetween: ['grp-sf', 'grp-la', 'grp-lv'],
      date: '2026-05-16',
      category: 'food',
    },
    {
      id: 'exp-5',
      description: 'Firewood (2 bundles)',
      amount: 30,
      currency: 'USD',
      paidBy: 'grp-sf',
      splitBetween: ['grp-sf', 'grp-la', 'grp-lv'],
      date: '2026-05-15',
      category: 'other',
    },
  ],
}
